config/routes.rb
AppForum::Application.routes.draw do

 resources :users
 

 resources :sessions, :only => [:new, :create, :destroy]
 resources :themes do
    resources :posts
 end

 

   match '/signup',  :to => 'users#new'
    match '/signout', :to => 'sessions#destroy'
   match '/about',   :to => 'pages#about'
   match '/signin',  :to => 'sessions#new'
  root :to => 'pages#home'

end

app/models/post.rb
class Post < ActiveRecord::Base
attr_accessible :content, :picture
   
   belongs_to :theme
   belongs_to :user
   default_scope :order => 'posts.created_at ASC'
     
  validates :content, :presence => true, :length => { :maximum => 140 }
  validates :theme_id, :presence => true
 validates :user_id, :presence => true
 
    has_attached_file :picture, 
                      :url  => "/assets/:id/:style/:basename.:extension",
                      :path => ":rails_root/public/assets/:id/:style/:basename.:extension",
                    #  :default_url => '/assets/rails.png',
                    
    :styles => { :medium => "400x300>" }

end

app/models/theme.rb
class Theme < ActiveRecord::Base
  attr_accessible :content
   
   belongs_to :user
   has_many :posts, :dependent => :destroy
   
  validates :content, :presence => true, :length => { :maximum => 140 }
  validates :user_id, :presence => true

    default_scope :order => 'themes.created_at DESC'
end

app/models/user.rb
class User < ActiveRecord::Base
 attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
   email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

   has_many :themes, :dependent => :destroy
   has_many :posts

  validates :name, :presence => true,
                   :length   => { :maximum => 50 }
  validates :email, :presence => true,
                    :format   => { :with => email_regex },
                   :uniqueness => { :case_sensitive => false }
   # Automatically create the virtual attribute 'password_confirmation'.
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }

 before_save :encrypt_password
      # Return true if the user's password matches the submitted password.
  def has_password?(submitted_password)
     encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end
 def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
	def feed #themes of curent user
	  themes
	end

 private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
   @title = "Home"
   @feed_items = Theme.paginate(:page => params[:page])
   if signed_in?
    @theme = Theme.new if signed_in?
    
   end
  end
  def about
   @title = "About"
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
def create
   @title = "New Post"
   @theme = Theme.find(params[:theme_id])
  

  
   @post =current_user.posts.build(params[:post])
   @post.theme_id = params[:theme_id]
  

    if @post.save
      flash[:success] = "Post created!"
      redirect_to @theme
    else
      @posts = []
      render 'themes/show'
    end
end





end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end

  def create
	   user = User.authenticate(params[:session][:email],
		                       params[:session][:password])
	  if user.nil?
		 flash.now[:error] = "Invalid email/password combination."
		 @title="Sign in"
		render 'new' 
	  else
		 sign_in user
	     redirect_back_or user
	  end
  end

 def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_filter :authenticate

  def create
  @title = "New theme"
  @theme  = current_user.themes.build(params[:theme])
  
    if @theme.save
      flash[:success] = "Theme created!"
      redirect_to root_path
    else
      @feed_items = []
      render 'pages/home'
    end
  end

   def show
    @theme = Theme.find(params[:id])
    @posts = @theme.posts.paginate(:page => params[:page])
    @post = Post.new
    @title = @theme.content
   
   end


  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :authenticate, :only => [:index,:edit, :update]  
before_filter :correct_user, :only => [:edit, :update]

  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page])
  end
  def new
    @title = "Sign up"
    @user = User.new
  end
  def show
   @user = User.find(params[:id])
   @themes = @user.themes.paginate(:page => params[:page])
   @title = @user.name
  end
  def create
   @user=User.new(params[:user])
    if @user.save
         sign_in @user
       flash[:success] = "Welcome to the Sample App!"
      redirect_to @user #user_path
    else
      @title = "Sign up"
      render 'new'
    end
  end
  def edit
    @title = "Edit user"
  end
  def update
   
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end
private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  
    def authenticate
      deny_access unless signed_in?
    end

def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end



def current_user=(user)
    @current_user = user
  end
def current_user
    @current_user ||= user_from_remember_token
  end
 def signed_in?
    !current_user.nil?
  end
 def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

  def store_location
      session[:return_to] = request.fullpath
    end

    def clear_return_to
      session[:return_to] = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About",about_path %></li>
      <li><%= link_to "Home", root_path %></li>
    
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
       <% if signed_in? %>
      <li><%= link_to "Profile", current_user %></li>
      <li><%= link_to "Settings", edit_user_path(current_user) %></li>     
     <li><%= link_to "Users", users_path %></li> 
     <% end %>
      <li><%= link_to "About", about_path %></li>
     
      <% if signed_in? %>
      <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
     
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppForum | <%= @title %></title>
  <%= stylesheet_link_tag    "custom" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
 <%= stylesheet_link_tag 'custom', :media => 'screen' %>
</head>
<body >
 <div class="container">
	<header>
	  <%= image_tag("logo.png", :alt => "Forum App", :class => "round") %>
  <%= render 'layouts/header' %>
	</header>
      <section class="round">
     
       
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>


        <%= yield %>
      </section>
 <%= render 'layouts/footer' %>
 <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Forum Application</h1>



<p>
 Was created according to 
<%= link_to "Ruby on Rails Tutorial ", 'http://russian.railstutorial.org/' %>

</p>

app/views/pages/home.html.erb
<% if !signed_in? %>
<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

<%else %>
<table class="profile" summary="For signed-in users">
   
 <tr>
     <td class="main" >
      <h1 class="theme">Want create new theme?</h1>
        <%= render 'shared/theme_form' %>
      </td>

        <td class="sidebar round" rowspan="2" >
        
           <%= render 'shared/user_info' %>
      </td>
 </tr>

  <tr>
         <td class="feed">
             <%= render 'shared/feed' %>
         </td>
    
         
   
  
  </tr>
  
  </table>
<% end %>

app/views/posts/_post.html.erb
<tr class="theme">
 <td colspan="2" >
  <%= @theme.content %>
 </td>
</tr>

<tr>
  <td class="gravatar round">
    <%= gravatar_for current_user, :size => 40 %>
    <p>
      <%= link_to User.find_by_id(post.user_id).name, User.find_by_id(post.user_id) %>
   </p>
  </td>
  <td class="post round">
		<span><%=post.content %>   </span>
	    <p>
			<% if post.picture.exists? then %>   
			 <%= image_tag post.picture.url(:medium) %>
			<% end %>
	 
	    </p>
    
  </td>

 
  
</tr>
<tr class="timestamp">
  <td colspan="2" class="round">
         <span class="timestamp">
           Posted <%= time_ago_in_words(post.created_at) %> ago 
         </span>
  </td>
</tr>

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class=round>
    <h2><%= pluralize(object.errors.count, "error") %>
        prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
  <table class="themes" summary="User themes">
    <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
  </table>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
  <td class="gravatar round">
   <p>
      <%= link_to feed_item.user.name, feed_item.user %>
   </p>
  </td>
  <td class="theme round">
     <span><%=link_to feed_item.content, feed_item %></span>
  </td>
  
</tr>
<tr class="timestamp">
  <td colspan="2">
    <span class="timestamp">
     Theme posted <%= time_ago_in_words(feed_item.created_at) %> ago 
    </span>
  </td>
</tr>

app/views/shared/_post_form.html.erb
<%= form_for ([@theme, @post]),:html => {:multipart => true}, :url => theme_posts_path(@theme) do |f| %>
  <%= render 'shared/error_message', :object => @post %>
  <div class="field">
    <%= f.text_area :content, :rows=>10%>
  <p>
    <%= f.file_field :picture %>
  </p>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/shared/_theme_form.html.erb
<%= form_for @theme do |f| %>
  <%= render 'shared/error_message', :object => f.object %>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <%= gravatar_for current_user, :size => 30 %>
    <span class="user_name">
      <%= current_user.name %>
    </span>
    <span class="themes">
      <%= pluralize(current_user.themes.count, "themes") %>
    </span>
  </a>
</div>

app/views/themes/_theme.html.erb
<tr>
  <td class="theme round">
    <span class="content"><%=link_to theme.content, theme %></span>
  </td>
  
</tr>

<tr class="timestamp">
  <td class=" round">
   <span class="timestamp">
      Posted <%= time_ago_in_words(theme.created_at) %> ago 
    </span>
  </td>
</tr>

app/views/themes/show.html.erb
<table class="profile" summary="Profile information">

  <td class="feed" >
   <p>Theme name  </p>     
         <h1>    <%= @theme.content %> </h1>
     <% unless @posts.empty? %>

        <table class="posts" summary="User posts"  cellspacing="10">

        <%= render @posts %>

        </table>
        <%= will_paginate @posts %>
      <% end %>
   </td>
    
     <td class="sidebar round">
        <%= render 'shared/user_info' %>
     </td>
  </tr>
 <tr>
  
   <td class="main" >
         
        <h2 class="theme">Want create new post?</h2>
        <%= render 'shared/post_form' %>
    </td>
 </tr>
 

  
   
</table>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_message', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<div>
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails">change</a>
</div>

app/views/users/index.html.erb
<h1>All users</h1>
<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, :size => 30 %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_message' %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>   

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
        <% unless @user.themes.empty? %>
        <table class="themes" summary="User themes">
          <%= render @themes %>
        </table>
        <%= will_paginate @themes %>
      <% end %>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %> <br/>
      <strong>Themes</strong> <%= @user.themes.count %> 
   </td>
  </tr>
</table>